### ISSUE TITLE
Difficulty in trying to get ~build-mobile-ghcs~ work for ghc 8.4.3

### ISSUE THREAD

**Issue by lingnand** [zw3rk/ghc-build-scripts#1]
Hi Moritz,

First a very big thank you for putting together all these very helpful materials + doing the presentation/slides on the cross compiling topics - they've been tremendous help to me so far on getting me off the ground.

Up until now I've been using your binary cross compiler distributions on http://hackage.mobilehaskell.org and they've been working great for me. However lately I've been running into some ghc bugs for 8.4.0 so had to look for ways now to compile newer versions of ghc (unfortunately their binary distros aren't on your website yet).

In trying to do so with your scripts, I've been hitting some roadblocks - they might just be due to my inexperience with the ghc build system.

## What I did

1. cloned the ghc source repository, checked out the `ghc-8.4` branch
2. I wasn't able to build `libffi` with your script either, so I opted to just go ahead and try out the ghc build
3. I did `cd <ghc-dir> && build-mobile-ghcs --prefix=<my-prefix> --iconv=<path/to/my/built/iconv> --clang=<path/to/my/clang-5.0.0> aarch64-android`
4. `hadrian` complains it doesn't recognize the flag `--build-root`
5. I edited `build-mobile-ghcs` by taking that flag out of the `hadrian`
6. `hadrian` now complains the below

```
Building aarch64-android...
Up to date
Up to date
shakeArgsWith   0.000s    0%                           
Function shake  0.142s   59%  =========================
Database read   0.000s    0%                           
With database   0.000s    0%                           
Running rules   0.098s   40%  =================        
Total           0.241s  100%                           
Error when running Shake build system:
* binary-dist
Error, file does not exist and no rule available:
  binary-dist
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:180:58 in shk-0.16.4-4b4fb1e3:Development.Shake.Internal.Rules.File
```

Now I'm at a temporary loss. Would you have any ideas on how to proceed from here?

**Comment by angerman** [comment]
Building the cross compilers is a non-trivial task (especially with the llvm-ng backend).  I'm currently trying to update the llvm-ng backend, and hope to have ghc 8.6 preview releases ready closely around the 8.6 alpha releases.

The primary issue is that hadrian got lots of new additions, ghc got a few new primops that the llvm-ng code gen needs to support, and the llvm-ng codegen being abysimal slow.

However, you can try to just build `stage2` with hadrian. All the binary distribution step would do is, take the `_build/{bin,lib}` folder and compress them.

**Comment by lingnand** [comment]
Tried building the cross compilers myself but like you said it's no easy task. I think I'll wait for your binary release when it's ready :)
